// Generated by CoffeeScript 1.6.3
var Log;

Log = (function() {
  function Log(selector) {
    this.element = document.querySelector(selector);
  }

  Log.prototype.write = function(message) {
    if (this.element) {
      this.element.textContent += "" + message + "\n";
      return this.element.scrollTop = this.element.scrollHeight;
    }
  };

  return Log;

})();
